version: '3.4'
services:
    yolox_ros:
        container_name: yolox_tensorrt
        # build: .
        image: fateshelled/tensorrt_yolox_ros:21.09-py3
        network_mode: host
        runtime: nvidia
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - $HOME/ros2_ws:/root/ros2_ws
            - /tmp/.X11-unix:/tmp/.X11-unix
        devices:
            - "/dev/video0:/dev/video0"
        working_dir: /root/ros2_ws
        tty: true
        command: bash

